#define PERMISSIVE_HOLD
#undef IGNORE_MOD_TAP_INTERRUPT	

#define TAPPING_TERM    200
#define TAPPING_TOGGLE  2

#define QMK_KEYS_PER_SCAN 6

#define MOUSEKEY_DELAY              50
#define MOUSEKEY_INTERVAL           15
#define MOUSEKEY_MAX_SPEED          4
#define MOUSEKEY_TIME_TO_MAX        50
#define MOUSEKEY_WHEEL_MAX_SPEED    1
#define MOUSEKEY_WHEEL_TIME_TO_MAX  50